server {
    listen 80;

    # Carpeta donde están los archivos compilados
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Intenta servir el archivo exacto; si no existe,
        # redirige todo a index.html (necesario para React Router)
        try_files $uri $uri/ /index.html;
    }
}
